<?php
// source: %A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%
		echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form = $_form = $this->global->formsCurrent = $this->global->uiControl["myForm"], []) ?>

<table>
	<tr>
		<th><?php if ($_label = $this->global->formsCurrent["input1"]->getLabel()) echo $_label ?></th>
		<td><?php echo $this->global->formsCurrent["input1"]->getControl() ?></td>
	</tr>
<?php
		$this->global->formsStack[] = $this->global->formsCurrent;
		$formContainer = $_form = $this->global->formsCurrent = $this->global->formsCurrent["cont1"] ?>
	<tr>
		<th><?php if ($_label = $this->global->formsCurrent["input2"]->getLabel()) echo $_label ?></th>
		<td><?php echo $this->global->formsCurrent["input2"]->getControl() ?></td>
	</tr>
	<tr>
		<th><?php if ($_label = $this->global->formsCurrent["input3"]->getLabel()) echo $_label ?></th>
		<td><?php echo $this->global->formsCurrent["input3"]->getControl() ?></td>
	</tr>
	<tr>
		<th>Checkboxes</th>
		<td>
<?php
		$this->global->formsStack[] = $this->global->formsCurrent;
		$formContainer = $_form = $this->global->formsCurrent = $this->global->formsCurrent["cont2"] ?>			<ol>
<?php
		$iterations = 0;
		if (isset($this->params['name'])) trigger_error('Variable $name overwritten in foreach.');
		if (isset($this->params['field'])) trigger_error('Variable $field overwritten in foreach.');
		foreach ($formContainer->controls AS $name => $field) {
			?>				<li><?php
			$_input = is_object($field) ? $field : $this->global->formsCurrent[$field];
			echo $_input->getControl() ?></li>
<?php
			$iterations++;
		}
		?>			</ol>
<?php $formContainer = $_form = $this->global->formsCurrent = array_pop($this->global->formsStack) ?>
		</td>
	</tr>
	<tr>
		<th><?php if ($_label = $this->global->formsCurrent["input7"]->getLabel()) echo $_label ?></th>
		<td><?php echo $this->global->formsCurrent["input7"]->getControl() ?></td>
	</tr>
<?php
		$formContainer = $_form = $this->global->formsCurrent = array_pop($this->global->formsStack);
		$this->global->formsStack[] = $this->global->formsCurrent;
		$formContainer = $_form = $this->global->formsCurrent = $this->global->formsCurrent["items"] ?>
	<tr>
		<th>Items</th>
		<td>
<?php
		$items = array(1, 2, 3);
		$iterations = 0;
		if (isset($this->params['item'])) trigger_error('Variable $item overwritten in foreach.');
		foreach ($items as $item) {
			if (!isset($formContainer[$item])) continue;
			$this->global->formsStack[] = $this->global->formsCurrent;
			$formContainer = $_form = $this->global->formsCurrent = is_object($item) ? $item : $this->global->formsCurrent[$item] ?>				<?php
			echo $this->global->formsCurrent["input"]->getControl() ?>

<?php
			$formContainer = $_form = $this->global->formsCurrent = array_pop($this->global->formsStack);
			$iterations++;
		}
		?>
		</td>
	</tr>
<?php $formContainer = $_form = $this->global->formsCurrent = array_pop($this->global->formsStack) ?>
	<tr>
		<th><?php if ($_label = $this->global->formsCurrent["input8"]->getLabel()) echo $_label ?></th>
		<td><?php echo $this->global->formsCurrent["input8"]->getControl() ?></td>
	</tr>
</table>
<?php echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd($this->global->formsCurrent) ?>

<?php
	}

}
