<?php
%A%
		echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form = $_form = $this->global->uiControl["myForm"], []);
		echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd($_form) ?>


<form<?php
		echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form = $_form = $this->global->uiControl["myForm"], array (
		), FALSE) ?>>
<?php echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd($_form, FALSE) ?></form>
<?php
%A%
