<?php
%A%
		/* line 1 */
		echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form = $_form = $this->global->formsStack[] = $this->global->uiControl["myForm"], ['id' => 'myForm', 'class'=>"ajax"]);
?>

<?php
		$iterations = 0;
		foreach (['id', 'username', 'select', 'area', 'send'] as $name) {
			?>		<?php
			$_input = is_object($name) ? $name : end($this->global->formsStack)[$name];
			if ($_label = $_input->getLabel()) echo $_label ?>

		<?php
			$_input = is_object($name) ? $name : end($this->global->formsStack)[$name];
			echo $_input->getControl()->addAttributes(['title' => 'Hello', 'size' => 10]) /* line 4 */ ?>

		<?php
			echo LR\Filters::escapeHtmlText($_input->getError());
?>

		<?php
			$_input = is_object($name) ? $name : end($this->global->formsStack)[$name];
			echo LR\Filters::escapeHtmlText($_input->getError());
?>


		<br>

		<?php
			$_input = is_object($form[$name]) ? $form[$name] : end($this->global->formsStack)[$form[$name]];
			if ($_label = $_input->getLabel()) echo $_label->addAttributes(['title' => 'hello'])->startTag() ?> <?php
			$_input = is_object($form[$name]) ? $form[$name] : end($this->global->formsStack)[$form[$name]];
			echo $_input->getControl()->addAttributes(['title' => 'Hello', 'size' => 10]) /* line 10 */ ?> <?php
			if ($_label) echo $_label->endTag() ?>

		<?php
			$_input = is_object($form[$name]) ? $form[$name] : end($this->global->formsStack)[$form[$name]];
			echo LR\Filters::escapeHtmlText($_input->getError());
?>

<?php
			$iterations++;
		}
?>

	<?php
		$_input = is_object($form['username']) ? $form['username'] : end($this->global->formsStack)[$form['username']];
		if ($_label = $_input->getLabel()) echo $_label ?>


	<LABEL title=hello<?php
		$_input = end($this->global->formsStack)["username"];
		echo $_input->getLabelPart()->addAttributes(['title' => null])->attributes() ?>>Name</LABEL>
	<input value=val type class="hello"<?php
		$_input = end($this->global->formsStack)["username"];
		echo $_input->getControlPart()->addAttributes(['value' => null, 'type' => null, 'class' => null])->attributes() ?>>

	<label<?php
		$_input = is_object($form['username']) ? $form['username'] : end($this->global->formsStack)[$form['username']];
		echo $_input->getLabelPart()->attributes() ?>></label>
	<label<?php
		$_input = is_object($form['username']) ? $form['username'] : end($this->global->formsStack)[$form['username']];
		echo $_input->getLabelPart()->attributes() ?>><?php echo $_input->getLabelPart()->getHtml() ?></label>
	<input<?php
		$_input = is_object($form['username']) ? $form['username'] : end($this->global->formsStack)[$form['username']];
		echo $_input->getControlPart()->attributes() ?>>

	<?php
		if ($_label = end($this->global->formsStack)["my"]->getLabel()) echo $_label;
		echo end($this->global->formsStack)["my"]->getControl() /* line 23 */ ?>

<?php
		echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack));
?>



<?php
		/* line 27 */
		echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form = $_form = $this->global->formsStack[] = $this->global->uiControl["myForm"], []);
		echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack));
?>


<?php
		/* line 29 */
		echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form = $_form = $this->global->formsStack[] = $this->global->uiControl["myForm"], []);
?>

<?php
		$iterations = 0;
		foreach ($form['sex']->items as $key => $label) {
			?>	<?php if ($_label = end($this->global->formsStack)["sex"]->getLabelPart($key)) echo $_label->startTag() ?> <?php
			echo end($this->global->formsStack)["sex"]->getControlPart($key) /* line 32 */ ?> <?php
			echo LR\Filters::escapeHtmlText($label) /* line 32 */;
			if ($_label) echo $_label->endTag() ?>

	<label title=hello<?php
			$_input = end($this->global->formsStack)["sex"];
			echo $_input->getLabelPart($key)->addAttributes(['title' => null])->attributes() ?>> <input<?php
			$_input = end($this->global->formsStack)["sex"];
			echo $_input->getControlPart($key)->attributes() ?>> </label>
<?php
			$iterations++;
		}
		?><label<?php
		$_input = end($this->global->formsStack)["sex"];
		echo $_input->getLabelPart()->attributes() ?>></label>
<label<?php
		$_input = end($this->global->formsStack)["sex"];
		echo $_input->getLabelPart()->attributes() ?>><?php echo $_input->getLabelPart()->getHtml() ?></label>
<label title="hello"<?php
		$_input = end($this->global->formsStack)["sex"];
		echo $_input->getLabelPart()->addAttributes(['title' => null])->attributes() ?>><?php echo $_input->getLabelPart()->getHtml() ?></label>


<?php if ($_label = end($this->global->formsStack)["checkbox"]->getLabelPart("")) echo $_label->startTag() ?> <?php
		echo end($this->global->formsStack)["checkbox"]->getControlPart("") /* line 41 */ ?> Label<?php if ($_label) echo $_label->endTag() ?>

<label title=hello<?php
		$_input = end($this->global->formsStack)["checkbox"];
		echo $_input->getLabelPart("")->addAttributes(['title' => null])->attributes() ?>> <input<?php
		$_input = end($this->global->formsStack)["checkbox"];
		echo $_input->getControlPart("")->attributes() ?>> </label>
<label title=hello<?php
		$_input = end($this->global->formsStack)["checkbox"];
		echo $_input->getLabelPart()->addAttributes(['title' => null])->attributes() ?>> <input<?php
		$_input = end($this->global->formsStack)["checkbox"];
		echo $_input->getControlPart()->attributes() ?>> </label>
<label<?php
		$_input = end($this->global->formsStack)["checkbox"];
		echo $_input->getLabelPart("")->attributes() ?>><?php echo $_input->getLabelPart()->getHtml() ?></label>
<label title=hello<?php
		$_input = end($this->global->formsStack)["checkbox"];
		echo $_input->getLabelPart()->addAttributes(['title' => null])->attributes() ?>><?php echo $_input->getLabelPart()->getHtml() ?></label>


<?php
		$iterations = 0;
		foreach ($form['checklist']->items as $key => $label) {
			?>	<?php if ($_label = end($this->global->formsStack)["checklist"]->getLabelPart($key)) echo $_label->startTag() ?> <?php
			echo end($this->global->formsStack)["checklist"]->getControlPart($key) /* line 50 */ ?> <?php
			echo LR\Filters::escapeHtmlText($label) /* line 50 */;
			if ($_label) echo $_label->endTag() ?>

	<label<?php
			$_input = end($this->global->formsStack)["checklist"];
			echo $_input->getLabelPart($key)->attributes() ?>> <input title=hello<?php
			$_input = end($this->global->formsStack)["checklist"];
			echo $_input->getControlPart($key)->addAttributes(['title' => null])->attributes() ?>> </label>
<?php
			$iterations++;
		}
		?><label<?php
		$_input = end($this->global->formsStack)["checklist"];
		echo $_input->getLabelPart()->attributes() ?>></label>
<label<?php
		$_input = end($this->global->formsStack)["checklist"];
		echo $_input->getLabelPart()->attributes() ?>><?php echo $_input->getLabelPart()->getHtml() ?></label>
<label title="hello"<?php
		$_input = end($this->global->formsStack)["checklist"];
		echo $_input->getLabelPart()->addAttributes(['title' => null])->attributes() ?>><?php echo $_input->getLabelPart()->getHtml() ?></label>


<?php
		$form = $_form = $this->global->formsStack[] = $this->global->uiControl["myForm"];
		if (1) {
			?><form id="myForm" class="ajax"<?php echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin(end($this->global->formsStack), ['id' => null, 'class' => null], false) ?>>
	<input<?php
			$_input = end($this->global->formsStack)["username"];
			echo $_input->getControlPart()->attributes() ?>>
<?php
			echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack), false);
?></form>
<?php
		}
?>


<?php
		$form = $_form = $this->global->formsStack[] = $this->global->uiControl["myForm"];
		?><form<?php
		echo ($_tmp = array_filter(['nclass'])) ? ' class="' . LR\Filters::escapeHtmlAttr(implode(" ", array_unique($_tmp))) . '"' : "";
		echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin(end($this->global->formsStack), ['class' => null], false) ?>>
	<input<?php
		$_input = end($this->global->formsStack)["username"];
		echo $_input->getControlPart()->addAttributes(['class' => null])->attributes();
		echo ($_tmp = array_filter(['nclass'])) ? ' class="' . LR\Filters::escapeHtmlAttr(implode(" ", array_unique($_tmp))) . '"' : "";
?>>
<?php
		echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack), false);
?></form>


<?php
		$form = $_form = $this->global->formsStack[] = is_object($this->global->uiControl['myForm']) ? $this->global->uiControl['myForm'] : $this->global->uiControl[$this->global->uiControl['myForm']];
		?><FORM<?php echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin(end($this->global->formsStack), [], false) ?>>
	<input<?php
		$_input = end($this->global->formsStack)["username"];
		echo $_input->getControlPart()->attributes() ?>>
<?php
		echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack), false);
?></FORM>


<select<?php
		$_input = end($this->global->formsStack)["select"];
		echo $_input->getControlPart()->attributes() ?>><?php echo $_input->getControl()->getHtml() ?></select>


<textarea title="<?php echo LR\Filters::escapeHtmlAttr(10) /* line 76 */ ?>"<?php
		$_input = end($this->global->formsStack)["area"];
		echo $_input->getControlPart()->addAttributes(['title' => null])->attributes() ?>><?php echo $_input->getControl()->getHtml() ?></textarea>


<select<?php
		$_input = end($this->global->formsStack)["select"];
		echo $_input->getControlPart()->attributes() ?>><?php echo $_input->getControl()->getHtml() ?></select>
<?php
		echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack));
?>



<?php
		$form = $this->global->formsStack[] = $this->global->uiControl["myForm"];
		?><label<?php
		$_input = end($this->global->formsStack)["sex"];
		echo $_input->getLabelPart()->attributes() ?>><?php echo $_input->getLabelPart()->getHtml() ?></label>
<input<?php
		$_input = end($this->global->formsStack)["username"];
		echo $_input->getControlPart()->attributes() ?>>
<?php
		array_pop($this->global->formsStack);
%A%
