<?php
// source: %A%

class Template%a% extends Latte\Template
{

	function render()
	{
%A%
		echo Nette\Bridges\FormsLatte\Runtime::renderFormBegin($form = $_form = $this->global->formsStack[] = $this->global->uiControl["myForm"], []) ?>

<table>
	<tr>
		<th><?php if ($_label = end($this->global->formsStack)["input1"]->getLabel()) echo $_label ?></th>
		<td><?php echo end($this->global->formsStack)["input1"]->getControl() ?></td>
	</tr>
<?php $this->global->formsStack[] = $formContainer = $_form = end($this->global->formsStack)["cont1"] ?>
	<tr>
		<th><?php if ($_label = end($this->global->formsStack)["input2"]->getLabel()) echo $_label ?></th>
		<td><?php echo end($this->global->formsStack)["input2"]->getControl() ?></td>
	</tr>
	<tr>
		<th><?php if ($_label = end($this->global->formsStack)["input3"]->getLabel()) echo $_label ?></th>
		<td><?php echo end($this->global->formsStack)["input3"]->getControl() ?></td>
	</tr>
	<tr>
		<th>Checkboxes</th>
		<td>
<?php $this->global->formsStack[] = $formContainer = $_form = end($this->global->formsStack)["cont2"] ?>			<ol>
<?php
		$iterations = 0;
		if (isset($this->params['name'])) trigger_error('Variable $name overwritten in foreach.');
		if (isset($this->params['field'])) trigger_error('Variable $field overwritten in foreach.');
		foreach ($formContainer->controls AS $name => $field) {
			?>				<li><?php
			$_input = is_object($field) ? $field : end($this->global->formsStack)[$field];
			echo $_input->getControl() ?></li>
<?php
			$iterations++;
		}
		?>			</ol>
<?php
		array_pop($this->global->formsStack);
		$formContainer = $_form = end($this->global->formsStack) ?>
		</td>
	</tr>
	<tr>
		<th><?php if ($_label = end($this->global->formsStack)["input7"]->getLabel()) echo $_label ?></th>
		<td><?php echo end($this->global->formsStack)["input7"]->getControl() ?></td>
	</tr>
<?php
		array_pop($this->global->formsStack);
		$formContainer = $_form = end($this->global->formsStack);
		$this->global->formsStack[] = $formContainer = $_form = end($this->global->formsStack)["items"] ?>
	<tr>
		<th>Items</th>
		<td>
<?php
		$items = array(1, 2, 3);
		$iterations = 0;
		if (isset($this->params['item'])) trigger_error('Variable $item overwritten in foreach.');
		foreach ($items as $item) {
			if (!isset($formContainer[$item])) continue;
			$this->global->formsStack[] = $formContainer = $_form = is_object($item) ? $item : end($this->global->formsStack)[$item] ?>				<?php
			echo end($this->global->formsStack)["input"]->getControl() ?>

<?php
			array_pop($this->global->formsStack);
			$formContainer = $_form = end($this->global->formsStack);
			$iterations++;
		}
		?>
		</td>
	</tr>
<?php
		array_pop($this->global->formsStack);
		$formContainer = $_form = end($this->global->formsStack) ?>
	<tr>
		<th><?php if ($_label = end($this->global->formsStack)["input8"]->getLabel()) echo $_label ?></th>
		<td><?php echo end($this->global->formsStack)["input8"]->getControl() ?></td>
	</tr>
</table>
<?php
		echo Nette\Bridges\FormsLatte\Runtime::renderFormEnd(array_pop($this->global->formsStack));
		?>

<?php
	}

}
